#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BromoAirlines
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BromoAirlines")]
	public partial class DataBaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAkun(Akun instance);
    partial void UpdateAkun(Akun instance);
    partial void DeleteAkun(Akun instance);
    partial void InsertBandara(Bandara instance);
    partial void UpdateBandara(Bandara instance);
    partial void DeleteBandara(Bandara instance);
    partial void InsertJadwalPenerbangan(JadwalPenerbangan instance);
    partial void UpdateJadwalPenerbangan(JadwalPenerbangan instance);
    partial void DeleteJadwalPenerbangan(JadwalPenerbangan instance);
    partial void InsertKodePromo(KodePromo instance);
    partial void UpdateKodePromo(KodePromo instance);
    partial void DeleteKodePromo(KodePromo instance);
    partial void InsertMaskapai(Maskapai instance);
    partial void UpdateMaskapai(Maskapai instance);
    partial void DeleteMaskapai(Maskapai instance);
    partial void InsertNegara(Negara instance);
    partial void UpdateNegara(Negara instance);
    partial void DeleteNegara(Negara instance);
    partial void InsertStatusPenerbangan(StatusPenerbangan instance);
    partial void UpdateStatusPenerbangan(StatusPenerbangan instance);
    partial void DeleteStatusPenerbangan(StatusPenerbangan instance);
    partial void InsertPerubahanStatusJadwalPenerbangan(PerubahanStatusJadwalPenerbangan instance);
    partial void UpdatePerubahanStatusJadwalPenerbangan(PerubahanStatusJadwalPenerbangan instance);
    partial void DeletePerubahanStatusJadwalPenerbangan(PerubahanStatusJadwalPenerbangan instance);
    partial void InsertTransaksiDetail(TransaksiDetail instance);
    partial void UpdateTransaksiDetail(TransaksiDetail instance);
    partial void DeleteTransaksiDetail(TransaksiDetail instance);
    partial void InsertTransaksiHeader(TransaksiHeader instance);
    partial void UpdateTransaksiHeader(TransaksiHeader instance);
    partial void DeleteTransaksiHeader(TransaksiHeader instance);
    #endregion
		
		public DataBaseDataContext() : 
				base(global::BromoAirlines.Properties.Settings.Default.BromoAirlinesConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataBaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Akun> Akuns
		{
			get
			{
				return this.GetTable<Akun>();
			}
		}
		
		public System.Data.Linq.Table<Bandara> Bandaras
		{
			get
			{
				return this.GetTable<Bandara>();
			}
		}
		
		public System.Data.Linq.Table<JadwalPenerbangan> JadwalPenerbangans
		{
			get
			{
				return this.GetTable<JadwalPenerbangan>();
			}
		}
		
		public System.Data.Linq.Table<KodePromo> KodePromos
		{
			get
			{
				return this.GetTable<KodePromo>();
			}
		}
		
		public System.Data.Linq.Table<Maskapai> Maskapais
		{
			get
			{
				return this.GetTable<Maskapai>();
			}
		}
		
		public System.Data.Linq.Table<Negara> Negaras
		{
			get
			{
				return this.GetTable<Negara>();
			}
		}
		
		public System.Data.Linq.Table<StatusPenerbangan> StatusPenerbangans
		{
			get
			{
				return this.GetTable<StatusPenerbangan>();
			}
		}
		
		public System.Data.Linq.Table<PerubahanStatusJadwalPenerbangan> PerubahanStatusJadwalPenerbangans
		{
			get
			{
				return this.GetTable<PerubahanStatusJadwalPenerbangan>();
			}
		}
		
		public System.Data.Linq.Table<TransaksiDetail> TransaksiDetails
		{
			get
			{
				return this.GetTable<TransaksiDetail>();
			}
		}
		
		public System.Data.Linq.Table<TransaksiHeader> TransaksiHeaders
		{
			get
			{
				return this.GetTable<TransaksiHeader>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Akun")]
	public partial class Akun : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Username;
		
		private string _Password;
		
		private string _Nama;
		
		private System.DateTime _TanggalLahir;
		
		private string _NomorTelepon;
		
		private bool _MerupakanAdmin;
		
		private EntitySet<TransaksiHeader> _TransaksiHeaders;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnNamaChanging(string value);
    partial void OnNamaChanged();
    partial void OnTanggalLahirChanging(System.DateTime value);
    partial void OnTanggalLahirChanged();
    partial void OnNomorTeleponChanging(string value);
    partial void OnNomorTeleponChanged();
    partial void OnMerupakanAdminChanging(bool value);
    partial void OnMerupakanAdminChanged();
    #endregion
		
		public Akun()
		{
			this._TransaksiHeaders = new EntitySet<TransaksiHeader>(new Action<TransaksiHeader>(this.attach_TransaksiHeaders), new Action<TransaksiHeader>(this.detach_TransaksiHeaders));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nama", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Nama
		{
			get
			{
				return this._Nama;
			}
			set
			{
				if ((this._Nama != value))
				{
					this.OnNamaChanging(value);
					this.SendPropertyChanging();
					this._Nama = value;
					this.SendPropertyChanged("Nama");
					this.OnNamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TanggalLahir", DbType="Date NOT NULL")]
		public System.DateTime TanggalLahir
		{
			get
			{
				return this._TanggalLahir;
			}
			set
			{
				if ((this._TanggalLahir != value))
				{
					this.OnTanggalLahirChanging(value);
					this.SendPropertyChanging();
					this._TanggalLahir = value;
					this.SendPropertyChanged("TanggalLahir");
					this.OnTanggalLahirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomorTelepon", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NomorTelepon
		{
			get
			{
				return this._NomorTelepon;
			}
			set
			{
				if ((this._NomorTelepon != value))
				{
					this.OnNomorTeleponChanging(value);
					this.SendPropertyChanging();
					this._NomorTelepon = value;
					this.SendPropertyChanged("NomorTelepon");
					this.OnNomorTeleponChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MerupakanAdmin", DbType="Bit NOT NULL")]
		public bool MerupakanAdmin
		{
			get
			{
				return this._MerupakanAdmin;
			}
			set
			{
				if ((this._MerupakanAdmin != value))
				{
					this.OnMerupakanAdminChanging(value);
					this.SendPropertyChanging();
					this._MerupakanAdmin = value;
					this.SendPropertyChanged("MerupakanAdmin");
					this.OnMerupakanAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Akun_TransaksiHeader", Storage="_TransaksiHeaders", ThisKey="ID", OtherKey="AkunID")]
		public EntitySet<TransaksiHeader> TransaksiHeaders
		{
			get
			{
				return this._TransaksiHeaders;
			}
			set
			{
				this._TransaksiHeaders.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TransaksiHeaders(TransaksiHeader entity)
		{
			this.SendPropertyChanging();
			entity.Akun = this;
		}
		
		private void detach_TransaksiHeaders(TransaksiHeader entity)
		{
			this.SendPropertyChanging();
			entity.Akun = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Bandara")]
	public partial class Bandara : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Nama;
		
		private string _KodeIATA;
		
		private string _Kota;
		
		private int _NegaraID;
		
		private int _JumlahTerminal;
		
		private string _Alamat;
		
		private EntitySet<JadwalPenerbangan> _JadwalPenerbangans;
		
		private EntitySet<JadwalPenerbangan> _JadwalPenerbangans1;
		
		private EntityRef<Negara> _Negara;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNamaChanging(string value);
    partial void OnNamaChanged();
    partial void OnKodeIATAChanging(string value);
    partial void OnKodeIATAChanged();
    partial void OnKotaChanging(string value);
    partial void OnKotaChanged();
    partial void OnNegaraIDChanging(int value);
    partial void OnNegaraIDChanged();
    partial void OnJumlahTerminalChanging(int value);
    partial void OnJumlahTerminalChanged();
    partial void OnAlamatChanging(string value);
    partial void OnAlamatChanged();
    #endregion
		
		public Bandara()
		{
			this._JadwalPenerbangans = new EntitySet<JadwalPenerbangan>(new Action<JadwalPenerbangan>(this.attach_JadwalPenerbangans), new Action<JadwalPenerbangan>(this.detach_JadwalPenerbangans));
			this._JadwalPenerbangans1 = new EntitySet<JadwalPenerbangan>(new Action<JadwalPenerbangan>(this.attach_JadwalPenerbangans1), new Action<JadwalPenerbangan>(this.detach_JadwalPenerbangans1));
			this._Negara = default(EntityRef<Negara>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nama", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Nama
		{
			get
			{
				return this._Nama;
			}
			set
			{
				if ((this._Nama != value))
				{
					this.OnNamaChanging(value);
					this.SendPropertyChanging();
					this._Nama = value;
					this.SendPropertyChanged("Nama");
					this.OnNamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KodeIATA", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string KodeIATA
		{
			get
			{
				return this._KodeIATA;
			}
			set
			{
				if ((this._KodeIATA != value))
				{
					this.OnKodeIATAChanging(value);
					this.SendPropertyChanging();
					this._KodeIATA = value;
					this.SendPropertyChanged("KodeIATA");
					this.OnKodeIATAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kota", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Kota
		{
			get
			{
				return this._Kota;
			}
			set
			{
				if ((this._Kota != value))
				{
					this.OnKotaChanging(value);
					this.SendPropertyChanging();
					this._Kota = value;
					this.SendPropertyChanged("Kota");
					this.OnKotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NegaraID", DbType="Int NOT NULL")]
		public int NegaraID
		{
			get
			{
				return this._NegaraID;
			}
			set
			{
				if ((this._NegaraID != value))
				{
					if (this._Negara.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNegaraIDChanging(value);
					this.SendPropertyChanging();
					this._NegaraID = value;
					this.SendPropertyChanged("NegaraID");
					this.OnNegaraIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JumlahTerminal", DbType="Int NOT NULL")]
		public int JumlahTerminal
		{
			get
			{
				return this._JumlahTerminal;
			}
			set
			{
				if ((this._JumlahTerminal != value))
				{
					this.OnJumlahTerminalChanging(value);
					this.SendPropertyChanging();
					this._JumlahTerminal = value;
					this.SendPropertyChanged("JumlahTerminal");
					this.OnJumlahTerminalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alamat", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Alamat
		{
			get
			{
				return this._Alamat;
			}
			set
			{
				if ((this._Alamat != value))
				{
					this.OnAlamatChanging(value);
					this.SendPropertyChanging();
					this._Alamat = value;
					this.SendPropertyChanged("Alamat");
					this.OnAlamatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Bandara_JadwalPenerbangan", Storage="_JadwalPenerbangans", ThisKey="ID", OtherKey="BandaraKeberangkatanID")]
		public EntitySet<JadwalPenerbangan> JadwalPenerbangans
		{
			get
			{
				return this._JadwalPenerbangans;
			}
			set
			{
				this._JadwalPenerbangans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Bandara_JadwalPenerbangan1", Storage="_JadwalPenerbangans1", ThisKey="ID", OtherKey="BandaraTujuanID")]
		public EntitySet<JadwalPenerbangan> JadwalPenerbangans1
		{
			get
			{
				return this._JadwalPenerbangans1;
			}
			set
			{
				this._JadwalPenerbangans1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Negara_Bandara", Storage="_Negara", ThisKey="NegaraID", OtherKey="ID", IsForeignKey=true)]
		public Negara Negara
		{
			get
			{
				return this._Negara.Entity;
			}
			set
			{
				Negara previousValue = this._Negara.Entity;
				if (((previousValue != value) 
							|| (this._Negara.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Negara.Entity = null;
						previousValue.Bandaras.Remove(this);
					}
					this._Negara.Entity = value;
					if ((value != null))
					{
						value.Bandaras.Add(this);
						this._NegaraID = value.ID;
					}
					else
					{
						this._NegaraID = default(int);
					}
					this.SendPropertyChanged("Negara");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_JadwalPenerbangans(JadwalPenerbangan entity)
		{
			this.SendPropertyChanging();
			entity.Bandara = this;
		}
		
		private void detach_JadwalPenerbangans(JadwalPenerbangan entity)
		{
			this.SendPropertyChanging();
			entity.Bandara = null;
		}
		
		private void attach_JadwalPenerbangans1(JadwalPenerbangan entity)
		{
			this.SendPropertyChanging();
			entity.Bandara1 = this;
		}
		
		private void detach_JadwalPenerbangans1(JadwalPenerbangan entity)
		{
			this.SendPropertyChanging();
			entity.Bandara1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.JadwalPenerbangan")]
	public partial class JadwalPenerbangan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _KodePenerbangan;
		
		private int _BandaraKeberangkatanID;
		
		private int _BandaraTujuanID;
		
		private int _MaskapaiID;
		
		private System.DateTime _TanggalWaktuKeberangkatan;
		
		private int _DurasiPenerbangan;
		
		private double _HargaPerTiket;
		
		private EntitySet<PerubahanStatusJadwalPenerbangan> _PerubahanStatusJadwalPenerbangans;
		
		private EntitySet<TransaksiHeader> _TransaksiHeaders;
		
		private EntityRef<Bandara> _Bandara;
		
		private EntityRef<Bandara> _Bandara1;
		
		private EntityRef<Maskapai> _Maskapai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnKodePenerbanganChanging(string value);
    partial void OnKodePenerbanganChanged();
    partial void OnBandaraKeberangkatanIDChanging(int value);
    partial void OnBandaraKeberangkatanIDChanged();
    partial void OnBandaraTujuanIDChanging(int value);
    partial void OnBandaraTujuanIDChanged();
    partial void OnMaskapaiIDChanging(int value);
    partial void OnMaskapaiIDChanged();
    partial void OnTanggalWaktuKeberangkatanChanging(System.DateTime value);
    partial void OnTanggalWaktuKeberangkatanChanged();
    partial void OnDurasiPenerbanganChanging(int value);
    partial void OnDurasiPenerbanganChanged();
    partial void OnHargaPerTiketChanging(double value);
    partial void OnHargaPerTiketChanged();
    #endregion
		
		public JadwalPenerbangan()
		{
			this._PerubahanStatusJadwalPenerbangans = new EntitySet<PerubahanStatusJadwalPenerbangan>(new Action<PerubahanStatusJadwalPenerbangan>(this.attach_PerubahanStatusJadwalPenerbangans), new Action<PerubahanStatusJadwalPenerbangan>(this.detach_PerubahanStatusJadwalPenerbangans));
			this._TransaksiHeaders = new EntitySet<TransaksiHeader>(new Action<TransaksiHeader>(this.attach_TransaksiHeaders), new Action<TransaksiHeader>(this.detach_TransaksiHeaders));
			this._Bandara = default(EntityRef<Bandara>);
			this._Bandara1 = default(EntityRef<Bandara>);
			this._Maskapai = default(EntityRef<Maskapai>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KodePenerbangan", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string KodePenerbangan
		{
			get
			{
				return this._KodePenerbangan;
			}
			set
			{
				if ((this._KodePenerbangan != value))
				{
					this.OnKodePenerbanganChanging(value);
					this.SendPropertyChanging();
					this._KodePenerbangan = value;
					this.SendPropertyChanged("KodePenerbangan");
					this.OnKodePenerbanganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BandaraKeberangkatanID", DbType="Int NOT NULL")]
		public int BandaraKeberangkatanID
		{
			get
			{
				return this._BandaraKeberangkatanID;
			}
			set
			{
				if ((this._BandaraKeberangkatanID != value))
				{
					if (this._Bandara.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBandaraKeberangkatanIDChanging(value);
					this.SendPropertyChanging();
					this._BandaraKeberangkatanID = value;
					this.SendPropertyChanged("BandaraKeberangkatanID");
					this.OnBandaraKeberangkatanIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BandaraTujuanID", DbType="Int NOT NULL")]
		public int BandaraTujuanID
		{
			get
			{
				return this._BandaraTujuanID;
			}
			set
			{
				if ((this._BandaraTujuanID != value))
				{
					if (this._Bandara1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBandaraTujuanIDChanging(value);
					this.SendPropertyChanging();
					this._BandaraTujuanID = value;
					this.SendPropertyChanged("BandaraTujuanID");
					this.OnBandaraTujuanIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaskapaiID", DbType="Int NOT NULL")]
		public int MaskapaiID
		{
			get
			{
				return this._MaskapaiID;
			}
			set
			{
				if ((this._MaskapaiID != value))
				{
					if (this._Maskapai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaskapaiIDChanging(value);
					this.SendPropertyChanging();
					this._MaskapaiID = value;
					this.SendPropertyChanged("MaskapaiID");
					this.OnMaskapaiIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TanggalWaktuKeberangkatan", DbType="DateTime NOT NULL")]
		public System.DateTime TanggalWaktuKeberangkatan
		{
			get
			{
				return this._TanggalWaktuKeberangkatan;
			}
			set
			{
				if ((this._TanggalWaktuKeberangkatan != value))
				{
					this.OnTanggalWaktuKeberangkatanChanging(value);
					this.SendPropertyChanging();
					this._TanggalWaktuKeberangkatan = value;
					this.SendPropertyChanged("TanggalWaktuKeberangkatan");
					this.OnTanggalWaktuKeberangkatanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DurasiPenerbangan", DbType="Int NOT NULL")]
		public int DurasiPenerbangan
		{
			get
			{
				return this._DurasiPenerbangan;
			}
			set
			{
				if ((this._DurasiPenerbangan != value))
				{
					this.OnDurasiPenerbanganChanging(value);
					this.SendPropertyChanging();
					this._DurasiPenerbangan = value;
					this.SendPropertyChanged("DurasiPenerbangan");
					this.OnDurasiPenerbanganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HargaPerTiket", DbType="Float NOT NULL")]
		public double HargaPerTiket
		{
			get
			{
				return this._HargaPerTiket;
			}
			set
			{
				if ((this._HargaPerTiket != value))
				{
					this.OnHargaPerTiketChanging(value);
					this.SendPropertyChanging();
					this._HargaPerTiket = value;
					this.SendPropertyChanged("HargaPerTiket");
					this.OnHargaPerTiketChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="JadwalPenerbangan_PerubahanStatusJadwalPenerbangan", Storage="_PerubahanStatusJadwalPenerbangans", ThisKey="ID", OtherKey="JadwalPenerbanganID")]
		public EntitySet<PerubahanStatusJadwalPenerbangan> PerubahanStatusJadwalPenerbangans
		{
			get
			{
				return this._PerubahanStatusJadwalPenerbangans;
			}
			set
			{
				this._PerubahanStatusJadwalPenerbangans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="JadwalPenerbangan_TransaksiHeader", Storage="_TransaksiHeaders", ThisKey="ID", OtherKey="JadwalPenerbanganID")]
		public EntitySet<TransaksiHeader> TransaksiHeaders
		{
			get
			{
				return this._TransaksiHeaders;
			}
			set
			{
				this._TransaksiHeaders.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Bandara_JadwalPenerbangan", Storage="_Bandara", ThisKey="BandaraKeberangkatanID", OtherKey="ID", IsForeignKey=true)]
		public Bandara Bandara
		{
			get
			{
				return this._Bandara.Entity;
			}
			set
			{
				Bandara previousValue = this._Bandara.Entity;
				if (((previousValue != value) 
							|| (this._Bandara.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Bandara.Entity = null;
						previousValue.JadwalPenerbangans.Remove(this);
					}
					this._Bandara.Entity = value;
					if ((value != null))
					{
						value.JadwalPenerbangans.Add(this);
						this._BandaraKeberangkatanID = value.ID;
					}
					else
					{
						this._BandaraKeberangkatanID = default(int);
					}
					this.SendPropertyChanged("Bandara");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Bandara_JadwalPenerbangan1", Storage="_Bandara1", ThisKey="BandaraTujuanID", OtherKey="ID", IsForeignKey=true)]
		public Bandara Bandara1
		{
			get
			{
				return this._Bandara1.Entity;
			}
			set
			{
				Bandara previousValue = this._Bandara1.Entity;
				if (((previousValue != value) 
							|| (this._Bandara1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Bandara1.Entity = null;
						previousValue.JadwalPenerbangans1.Remove(this);
					}
					this._Bandara1.Entity = value;
					if ((value != null))
					{
						value.JadwalPenerbangans1.Add(this);
						this._BandaraTujuanID = value.ID;
					}
					else
					{
						this._BandaraTujuanID = default(int);
					}
					this.SendPropertyChanged("Bandara1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Maskapai_JadwalPenerbangan", Storage="_Maskapai", ThisKey="MaskapaiID", OtherKey="ID", IsForeignKey=true)]
		public Maskapai Maskapai
		{
			get
			{
				return this._Maskapai.Entity;
			}
			set
			{
				Maskapai previousValue = this._Maskapai.Entity;
				if (((previousValue != value) 
							|| (this._Maskapai.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Maskapai.Entity = null;
						previousValue.JadwalPenerbangans.Remove(this);
					}
					this._Maskapai.Entity = value;
					if ((value != null))
					{
						value.JadwalPenerbangans.Add(this);
						this._MaskapaiID = value.ID;
					}
					else
					{
						this._MaskapaiID = default(int);
					}
					this.SendPropertyChanged("Maskapai");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PerubahanStatusJadwalPenerbangans(PerubahanStatusJadwalPenerbangan entity)
		{
			this.SendPropertyChanging();
			entity.JadwalPenerbangan = this;
		}
		
		private void detach_PerubahanStatusJadwalPenerbangans(PerubahanStatusJadwalPenerbangan entity)
		{
			this.SendPropertyChanging();
			entity.JadwalPenerbangan = null;
		}
		
		private void attach_TransaksiHeaders(TransaksiHeader entity)
		{
			this.SendPropertyChanging();
			entity.JadwalPenerbangan = this;
		}
		
		private void detach_TransaksiHeaders(TransaksiHeader entity)
		{
			this.SendPropertyChanging();
			entity.JadwalPenerbangan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KodePromo")]
	public partial class KodePromo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Kode;
		
		private double _PersentaseDiskon;
		
		private double _MaksimumDiskon;
		
		private System.DateTime _BerlakuSampai;
		
		private string _Deskripsi;
		
		private EntitySet<TransaksiHeader> _TransaksiHeaders;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnKodeChanging(string value);
    partial void OnKodeChanged();
    partial void OnPersentaseDiskonChanging(double value);
    partial void OnPersentaseDiskonChanged();
    partial void OnMaksimumDiskonChanging(double value);
    partial void OnMaksimumDiskonChanged();
    partial void OnBerlakuSampaiChanging(System.DateTime value);
    partial void OnBerlakuSampaiChanged();
    partial void OnDeskripsiChanging(string value);
    partial void OnDeskripsiChanged();
    #endregion
		
		public KodePromo()
		{
			this._TransaksiHeaders = new EntitySet<TransaksiHeader>(new Action<TransaksiHeader>(this.attach_TransaksiHeaders), new Action<TransaksiHeader>(this.detach_TransaksiHeaders));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kode", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Kode
		{
			get
			{
				return this._Kode;
			}
			set
			{
				if ((this._Kode != value))
				{
					this.OnKodeChanging(value);
					this.SendPropertyChanging();
					this._Kode = value;
					this.SendPropertyChanged("Kode");
					this.OnKodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersentaseDiskon", DbType="Float NOT NULL")]
		public double PersentaseDiskon
		{
			get
			{
				return this._PersentaseDiskon;
			}
			set
			{
				if ((this._PersentaseDiskon != value))
				{
					this.OnPersentaseDiskonChanging(value);
					this.SendPropertyChanging();
					this._PersentaseDiskon = value;
					this.SendPropertyChanged("PersentaseDiskon");
					this.OnPersentaseDiskonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaksimumDiskon", DbType="Float NOT NULL")]
		public double MaksimumDiskon
		{
			get
			{
				return this._MaksimumDiskon;
			}
			set
			{
				if ((this._MaksimumDiskon != value))
				{
					this.OnMaksimumDiskonChanging(value);
					this.SendPropertyChanging();
					this._MaksimumDiskon = value;
					this.SendPropertyChanged("MaksimumDiskon");
					this.OnMaksimumDiskonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BerlakuSampai", DbType="Date NOT NULL")]
		public System.DateTime BerlakuSampai
		{
			get
			{
				return this._BerlakuSampai;
			}
			set
			{
				if ((this._BerlakuSampai != value))
				{
					this.OnBerlakuSampaiChanging(value);
					this.SendPropertyChanging();
					this._BerlakuSampai = value;
					this.SendPropertyChanged("BerlakuSampai");
					this.OnBerlakuSampaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deskripsi", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Deskripsi
		{
			get
			{
				return this._Deskripsi;
			}
			set
			{
				if ((this._Deskripsi != value))
				{
					this.OnDeskripsiChanging(value);
					this.SendPropertyChanging();
					this._Deskripsi = value;
					this.SendPropertyChanged("Deskripsi");
					this.OnDeskripsiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KodePromo_TransaksiHeader", Storage="_TransaksiHeaders", ThisKey="ID", OtherKey="KodePromoID")]
		public EntitySet<TransaksiHeader> TransaksiHeaders
		{
			get
			{
				return this._TransaksiHeaders;
			}
			set
			{
				this._TransaksiHeaders.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TransaksiHeaders(TransaksiHeader entity)
		{
			this.SendPropertyChanging();
			entity.KodePromo = this;
		}
		
		private void detach_TransaksiHeaders(TransaksiHeader entity)
		{
			this.SendPropertyChanging();
			entity.KodePromo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Maskapai")]
	public partial class Maskapai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Nama;
		
		private string _Perusahaan;
		
		private int _JumlahKru;
		
		private string _Deskripsi;
		
		private EntitySet<JadwalPenerbangan> _JadwalPenerbangans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNamaChanging(string value);
    partial void OnNamaChanged();
    partial void OnPerusahaanChanging(string value);
    partial void OnPerusahaanChanged();
    partial void OnJumlahKruChanging(int value);
    partial void OnJumlahKruChanged();
    partial void OnDeskripsiChanging(string value);
    partial void OnDeskripsiChanged();
    #endregion
		
		public Maskapai()
		{
			this._JadwalPenerbangans = new EntitySet<JadwalPenerbangan>(new Action<JadwalPenerbangan>(this.attach_JadwalPenerbangans), new Action<JadwalPenerbangan>(this.detach_JadwalPenerbangans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nama", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Nama
		{
			get
			{
				return this._Nama;
			}
			set
			{
				if ((this._Nama != value))
				{
					this.OnNamaChanging(value);
					this.SendPropertyChanging();
					this._Nama = value;
					this.SendPropertyChanged("Nama");
					this.OnNamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Perusahaan", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Perusahaan
		{
			get
			{
				return this._Perusahaan;
			}
			set
			{
				if ((this._Perusahaan != value))
				{
					this.OnPerusahaanChanging(value);
					this.SendPropertyChanging();
					this._Perusahaan = value;
					this.SendPropertyChanged("Perusahaan");
					this.OnPerusahaanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JumlahKru", DbType="Int NOT NULL")]
		public int JumlahKru
		{
			get
			{
				return this._JumlahKru;
			}
			set
			{
				if ((this._JumlahKru != value))
				{
					this.OnJumlahKruChanging(value);
					this.SendPropertyChanging();
					this._JumlahKru = value;
					this.SendPropertyChanged("JumlahKru");
					this.OnJumlahKruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deskripsi", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Deskripsi
		{
			get
			{
				return this._Deskripsi;
			}
			set
			{
				if ((this._Deskripsi != value))
				{
					this.OnDeskripsiChanging(value);
					this.SendPropertyChanging();
					this._Deskripsi = value;
					this.SendPropertyChanged("Deskripsi");
					this.OnDeskripsiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Maskapai_JadwalPenerbangan", Storage="_JadwalPenerbangans", ThisKey="ID", OtherKey="MaskapaiID")]
		public EntitySet<JadwalPenerbangan> JadwalPenerbangans
		{
			get
			{
				return this._JadwalPenerbangans;
			}
			set
			{
				this._JadwalPenerbangans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_JadwalPenerbangans(JadwalPenerbangan entity)
		{
			this.SendPropertyChanging();
			entity.Maskapai = this;
		}
		
		private void detach_JadwalPenerbangans(JadwalPenerbangan entity)
		{
			this.SendPropertyChanging();
			entity.Maskapai = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Negara")]
	public partial class Negara : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Nama;
		
		private string _IbukotaNegara;
		
		private EntitySet<Bandara> _Bandaras;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNamaChanging(string value);
    partial void OnNamaChanged();
    partial void OnIbukotaNegaraChanging(string value);
    partial void OnIbukotaNegaraChanged();
    #endregion
		
		public Negara()
		{
			this._Bandaras = new EntitySet<Bandara>(new Action<Bandara>(this.attach_Bandaras), new Action<Bandara>(this.detach_Bandaras));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nama", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Nama
		{
			get
			{
				return this._Nama;
			}
			set
			{
				if ((this._Nama != value))
				{
					this.OnNamaChanging(value);
					this.SendPropertyChanging();
					this._Nama = value;
					this.SendPropertyChanged("Nama");
					this.OnNamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IbukotaNegara", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string IbukotaNegara
		{
			get
			{
				return this._IbukotaNegara;
			}
			set
			{
				if ((this._IbukotaNegara != value))
				{
					this.OnIbukotaNegaraChanging(value);
					this.SendPropertyChanging();
					this._IbukotaNegara = value;
					this.SendPropertyChanged("IbukotaNegara");
					this.OnIbukotaNegaraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Negara_Bandara", Storage="_Bandaras", ThisKey="ID", OtherKey="NegaraID")]
		public EntitySet<Bandara> Bandaras
		{
			get
			{
				return this._Bandaras;
			}
			set
			{
				this._Bandaras.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Bandaras(Bandara entity)
		{
			this.SendPropertyChanging();
			entity.Negara = this;
		}
		
		private void detach_Bandaras(Bandara entity)
		{
			this.SendPropertyChanging();
			entity.Negara = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StatusPenerbangan")]
	public partial class StatusPenerbangan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Nama;
		
		private EntitySet<PerubahanStatusJadwalPenerbangan> _PerubahanStatusJadwalPenerbangans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNamaChanging(string value);
    partial void OnNamaChanged();
    #endregion
		
		public StatusPenerbangan()
		{
			this._PerubahanStatusJadwalPenerbangans = new EntitySet<PerubahanStatusJadwalPenerbangan>(new Action<PerubahanStatusJadwalPenerbangan>(this.attach_PerubahanStatusJadwalPenerbangans), new Action<PerubahanStatusJadwalPenerbangan>(this.detach_PerubahanStatusJadwalPenerbangans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nama", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Nama
		{
			get
			{
				return this._Nama;
			}
			set
			{
				if ((this._Nama != value))
				{
					this.OnNamaChanging(value);
					this.SendPropertyChanging();
					this._Nama = value;
					this.SendPropertyChanged("Nama");
					this.OnNamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StatusPenerbangan_PerubahanStatusJadwalPenerbangan", Storage="_PerubahanStatusJadwalPenerbangans", ThisKey="ID", OtherKey="StatusPenerbanganID")]
		public EntitySet<PerubahanStatusJadwalPenerbangan> PerubahanStatusJadwalPenerbangans
		{
			get
			{
				return this._PerubahanStatusJadwalPenerbangans;
			}
			set
			{
				this._PerubahanStatusJadwalPenerbangans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PerubahanStatusJadwalPenerbangans(PerubahanStatusJadwalPenerbangan entity)
		{
			this.SendPropertyChanging();
			entity.StatusPenerbangan = this;
		}
		
		private void detach_PerubahanStatusJadwalPenerbangans(PerubahanStatusJadwalPenerbangan entity)
		{
			this.SendPropertyChanging();
			entity.StatusPenerbangan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PerubahanStatusJadwalPenerbangan")]
	public partial class PerubahanStatusJadwalPenerbangan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _JadwalPenerbanganID;
		
		private int _StatusPenerbanganID;
		
		private System.DateTime _WaktuPerubahanTerjadi;
		
		private System.Nullable<int> _PerkiraanDurasiDelay;
		
		private EntityRef<JadwalPenerbangan> _JadwalPenerbangan;
		
		private EntityRef<StatusPenerbangan> _StatusPenerbangan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnJadwalPenerbanganIDChanging(int value);
    partial void OnJadwalPenerbanganIDChanged();
    partial void OnStatusPenerbanganIDChanging(int value);
    partial void OnStatusPenerbanganIDChanged();
    partial void OnWaktuPerubahanTerjadiChanging(System.DateTime value);
    partial void OnWaktuPerubahanTerjadiChanged();
    partial void OnPerkiraanDurasiDelayChanging(System.Nullable<int> value);
    partial void OnPerkiraanDurasiDelayChanged();
    #endregion
		
		public PerubahanStatusJadwalPenerbangan()
		{
			this._JadwalPenerbangan = default(EntityRef<JadwalPenerbangan>);
			this._StatusPenerbangan = default(EntityRef<StatusPenerbangan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JadwalPenerbanganID", DbType="Int NOT NULL")]
		public int JadwalPenerbanganID
		{
			get
			{
				return this._JadwalPenerbanganID;
			}
			set
			{
				if ((this._JadwalPenerbanganID != value))
				{
					if (this._JadwalPenerbangan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnJadwalPenerbanganIDChanging(value);
					this.SendPropertyChanging();
					this._JadwalPenerbanganID = value;
					this.SendPropertyChanged("JadwalPenerbanganID");
					this.OnJadwalPenerbanganIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusPenerbanganID", DbType="Int NOT NULL")]
		public int StatusPenerbanganID
		{
			get
			{
				return this._StatusPenerbanganID;
			}
			set
			{
				if ((this._StatusPenerbanganID != value))
				{
					if (this._StatusPenerbangan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnStatusPenerbanganIDChanging(value);
					this.SendPropertyChanging();
					this._StatusPenerbanganID = value;
					this.SendPropertyChanged("StatusPenerbanganID");
					this.OnStatusPenerbanganIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WaktuPerubahanTerjadi", DbType="DateTime NOT NULL")]
		public System.DateTime WaktuPerubahanTerjadi
		{
			get
			{
				return this._WaktuPerubahanTerjadi;
			}
			set
			{
				if ((this._WaktuPerubahanTerjadi != value))
				{
					this.OnWaktuPerubahanTerjadiChanging(value);
					this.SendPropertyChanging();
					this._WaktuPerubahanTerjadi = value;
					this.SendPropertyChanged("WaktuPerubahanTerjadi");
					this.OnWaktuPerubahanTerjadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerkiraanDurasiDelay", DbType="Int")]
		public System.Nullable<int> PerkiraanDurasiDelay
		{
			get
			{
				return this._PerkiraanDurasiDelay;
			}
			set
			{
				if ((this._PerkiraanDurasiDelay != value))
				{
					this.OnPerkiraanDurasiDelayChanging(value);
					this.SendPropertyChanging();
					this._PerkiraanDurasiDelay = value;
					this.SendPropertyChanged("PerkiraanDurasiDelay");
					this.OnPerkiraanDurasiDelayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="JadwalPenerbangan_PerubahanStatusJadwalPenerbangan", Storage="_JadwalPenerbangan", ThisKey="JadwalPenerbanganID", OtherKey="ID", IsForeignKey=true)]
		public JadwalPenerbangan JadwalPenerbangan
		{
			get
			{
				return this._JadwalPenerbangan.Entity;
			}
			set
			{
				JadwalPenerbangan previousValue = this._JadwalPenerbangan.Entity;
				if (((previousValue != value) 
							|| (this._JadwalPenerbangan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._JadwalPenerbangan.Entity = null;
						previousValue.PerubahanStatusJadwalPenerbangans.Remove(this);
					}
					this._JadwalPenerbangan.Entity = value;
					if ((value != null))
					{
						value.PerubahanStatusJadwalPenerbangans.Add(this);
						this._JadwalPenerbanganID = value.ID;
					}
					else
					{
						this._JadwalPenerbanganID = default(int);
					}
					this.SendPropertyChanged("JadwalPenerbangan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StatusPenerbangan_PerubahanStatusJadwalPenerbangan", Storage="_StatusPenerbangan", ThisKey="StatusPenerbanganID", OtherKey="ID", IsForeignKey=true)]
		public StatusPenerbangan StatusPenerbangan
		{
			get
			{
				return this._StatusPenerbangan.Entity;
			}
			set
			{
				StatusPenerbangan previousValue = this._StatusPenerbangan.Entity;
				if (((previousValue != value) 
							|| (this._StatusPenerbangan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._StatusPenerbangan.Entity = null;
						previousValue.PerubahanStatusJadwalPenerbangans.Remove(this);
					}
					this._StatusPenerbangan.Entity = value;
					if ((value != null))
					{
						value.PerubahanStatusJadwalPenerbangans.Add(this);
						this._StatusPenerbanganID = value.ID;
					}
					else
					{
						this._StatusPenerbanganID = default(int);
					}
					this.SendPropertyChanged("StatusPenerbangan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TransaksiDetail")]
	public partial class TransaksiDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _TransaksiHeaderID;
		
		private string _TitelPenumpang;
		
		private string _NamaLengkapPenumpang;
		
		private EntityRef<TransaksiHeader> _TransaksiHeader;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTransaksiHeaderIDChanging(int value);
    partial void OnTransaksiHeaderIDChanged();
    partial void OnTitelPenumpangChanging(string value);
    partial void OnTitelPenumpangChanged();
    partial void OnNamaLengkapPenumpangChanging(string value);
    partial void OnNamaLengkapPenumpangChanged();
    #endregion
		
		public TransaksiDetail()
		{
			this._TransaksiHeader = default(EntityRef<TransaksiHeader>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransaksiHeaderID", DbType="Int NOT NULL")]
		public int TransaksiHeaderID
		{
			get
			{
				return this._TransaksiHeaderID;
			}
			set
			{
				if ((this._TransaksiHeaderID != value))
				{
					if (this._TransaksiHeader.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTransaksiHeaderIDChanging(value);
					this.SendPropertyChanging();
					this._TransaksiHeaderID = value;
					this.SendPropertyChanged("TransaksiHeaderID");
					this.OnTransaksiHeaderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TitelPenumpang", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string TitelPenumpang
		{
			get
			{
				return this._TitelPenumpang;
			}
			set
			{
				if ((this._TitelPenumpang != value))
				{
					this.OnTitelPenumpangChanging(value);
					this.SendPropertyChanging();
					this._TitelPenumpang = value;
					this.SendPropertyChanged("TitelPenumpang");
					this.OnTitelPenumpangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamaLengkapPenumpang", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string NamaLengkapPenumpang
		{
			get
			{
				return this._NamaLengkapPenumpang;
			}
			set
			{
				if ((this._NamaLengkapPenumpang != value))
				{
					this.OnNamaLengkapPenumpangChanging(value);
					this.SendPropertyChanging();
					this._NamaLengkapPenumpang = value;
					this.SendPropertyChanged("NamaLengkapPenumpang");
					this.OnNamaLengkapPenumpangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TransaksiHeader_TransaksiDetail", Storage="_TransaksiHeader", ThisKey="TransaksiHeaderID", OtherKey="ID", IsForeignKey=true)]
		public TransaksiHeader TransaksiHeader
		{
			get
			{
				return this._TransaksiHeader.Entity;
			}
			set
			{
				TransaksiHeader previousValue = this._TransaksiHeader.Entity;
				if (((previousValue != value) 
							|| (this._TransaksiHeader.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TransaksiHeader.Entity = null;
						previousValue.TransaksiDetails.Remove(this);
					}
					this._TransaksiHeader.Entity = value;
					if ((value != null))
					{
						value.TransaksiDetails.Add(this);
						this._TransaksiHeaderID = value.ID;
					}
					else
					{
						this._TransaksiHeaderID = default(int);
					}
					this.SendPropertyChanged("TransaksiHeader");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TransaksiHeader")]
	public partial class TransaksiHeader : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _AkunID;
		
		private System.DateTime _TanggalTransaksi;
		
		private int _JadwalPenerbanganID;
		
		private int _JumlahPenumpang;
		
		private double _TotalHarga;
		
		private System.Nullable<int> _KodePromoID;
		
		private EntitySet<TransaksiDetail> _TransaksiDetails;
		
		private EntityRef<Akun> _Akun;
		
		private EntityRef<JadwalPenerbangan> _JadwalPenerbangan;
		
		private EntityRef<KodePromo> _KodePromo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnAkunIDChanging(int value);
    partial void OnAkunIDChanged();
    partial void OnTanggalTransaksiChanging(System.DateTime value);
    partial void OnTanggalTransaksiChanged();
    partial void OnJadwalPenerbanganIDChanging(int value);
    partial void OnJadwalPenerbanganIDChanged();
    partial void OnJumlahPenumpangChanging(int value);
    partial void OnJumlahPenumpangChanged();
    partial void OnTotalHargaChanging(double value);
    partial void OnTotalHargaChanged();
    partial void OnKodePromoIDChanging(System.Nullable<int> value);
    partial void OnKodePromoIDChanged();
    #endregion
		
		public TransaksiHeader()
		{
			this._TransaksiDetails = new EntitySet<TransaksiDetail>(new Action<TransaksiDetail>(this.attach_TransaksiDetails), new Action<TransaksiDetail>(this.detach_TransaksiDetails));
			this._Akun = default(EntityRef<Akun>);
			this._JadwalPenerbangan = default(EntityRef<JadwalPenerbangan>);
			this._KodePromo = default(EntityRef<KodePromo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AkunID", DbType="Int NOT NULL")]
		public int AkunID
		{
			get
			{
				return this._AkunID;
			}
			set
			{
				if ((this._AkunID != value))
				{
					if (this._Akun.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAkunIDChanging(value);
					this.SendPropertyChanging();
					this._AkunID = value;
					this.SendPropertyChanged("AkunID");
					this.OnAkunIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TanggalTransaksi", DbType="DateTime NOT NULL")]
		public System.DateTime TanggalTransaksi
		{
			get
			{
				return this._TanggalTransaksi;
			}
			set
			{
				if ((this._TanggalTransaksi != value))
				{
					this.OnTanggalTransaksiChanging(value);
					this.SendPropertyChanging();
					this._TanggalTransaksi = value;
					this.SendPropertyChanged("TanggalTransaksi");
					this.OnTanggalTransaksiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JadwalPenerbanganID", DbType="Int NOT NULL")]
		public int JadwalPenerbanganID
		{
			get
			{
				return this._JadwalPenerbanganID;
			}
			set
			{
				if ((this._JadwalPenerbanganID != value))
				{
					if (this._JadwalPenerbangan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnJadwalPenerbanganIDChanging(value);
					this.SendPropertyChanging();
					this._JadwalPenerbanganID = value;
					this.SendPropertyChanged("JadwalPenerbanganID");
					this.OnJadwalPenerbanganIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JumlahPenumpang", DbType="Int NOT NULL")]
		public int JumlahPenumpang
		{
			get
			{
				return this._JumlahPenumpang;
			}
			set
			{
				if ((this._JumlahPenumpang != value))
				{
					this.OnJumlahPenumpangChanging(value);
					this.SendPropertyChanging();
					this._JumlahPenumpang = value;
					this.SendPropertyChanged("JumlahPenumpang");
					this.OnJumlahPenumpangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalHarga", DbType="Float NOT NULL")]
		public double TotalHarga
		{
			get
			{
				return this._TotalHarga;
			}
			set
			{
				if ((this._TotalHarga != value))
				{
					this.OnTotalHargaChanging(value);
					this.SendPropertyChanging();
					this._TotalHarga = value;
					this.SendPropertyChanged("TotalHarga");
					this.OnTotalHargaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KodePromoID", DbType="Int")]
		public System.Nullable<int> KodePromoID
		{
			get
			{
				return this._KodePromoID;
			}
			set
			{
				if ((this._KodePromoID != value))
				{
					if (this._KodePromo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKodePromoIDChanging(value);
					this.SendPropertyChanging();
					this._KodePromoID = value;
					this.SendPropertyChanged("KodePromoID");
					this.OnKodePromoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TransaksiHeader_TransaksiDetail", Storage="_TransaksiDetails", ThisKey="ID", OtherKey="TransaksiHeaderID")]
		public EntitySet<TransaksiDetail> TransaksiDetails
		{
			get
			{
				return this._TransaksiDetails;
			}
			set
			{
				this._TransaksiDetails.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Akun_TransaksiHeader", Storage="_Akun", ThisKey="AkunID", OtherKey="ID", IsForeignKey=true)]
		public Akun Akun
		{
			get
			{
				return this._Akun.Entity;
			}
			set
			{
				Akun previousValue = this._Akun.Entity;
				if (((previousValue != value) 
							|| (this._Akun.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Akun.Entity = null;
						previousValue.TransaksiHeaders.Remove(this);
					}
					this._Akun.Entity = value;
					if ((value != null))
					{
						value.TransaksiHeaders.Add(this);
						this._AkunID = value.ID;
					}
					else
					{
						this._AkunID = default(int);
					}
					this.SendPropertyChanged("Akun");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="JadwalPenerbangan_TransaksiHeader", Storage="_JadwalPenerbangan", ThisKey="JadwalPenerbanganID", OtherKey="ID", IsForeignKey=true)]
		public JadwalPenerbangan JadwalPenerbangan
		{
			get
			{
				return this._JadwalPenerbangan.Entity;
			}
			set
			{
				JadwalPenerbangan previousValue = this._JadwalPenerbangan.Entity;
				if (((previousValue != value) 
							|| (this._JadwalPenerbangan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._JadwalPenerbangan.Entity = null;
						previousValue.TransaksiHeaders.Remove(this);
					}
					this._JadwalPenerbangan.Entity = value;
					if ((value != null))
					{
						value.TransaksiHeaders.Add(this);
						this._JadwalPenerbanganID = value.ID;
					}
					else
					{
						this._JadwalPenerbanganID = default(int);
					}
					this.SendPropertyChanged("JadwalPenerbangan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KodePromo_TransaksiHeader", Storage="_KodePromo", ThisKey="KodePromoID", OtherKey="ID", IsForeignKey=true)]
		public KodePromo KodePromo
		{
			get
			{
				return this._KodePromo.Entity;
			}
			set
			{
				KodePromo previousValue = this._KodePromo.Entity;
				if (((previousValue != value) 
							|| (this._KodePromo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KodePromo.Entity = null;
						previousValue.TransaksiHeaders.Remove(this);
					}
					this._KodePromo.Entity = value;
					if ((value != null))
					{
						value.TransaksiHeaders.Add(this);
						this._KodePromoID = value.ID;
					}
					else
					{
						this._KodePromoID = default(Nullable<int>);
					}
					this.SendPropertyChanged("KodePromo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TransaksiDetails(TransaksiDetail entity)
		{
			this.SendPropertyChanging();
			entity.TransaksiHeader = this;
		}
		
		private void detach_TransaksiDetails(TransaksiDetail entity)
		{
			this.SendPropertyChanging();
			entity.TransaksiHeader = null;
		}
	}
}
#pragma warning restore 1591
